// Template data from text files
export const TEMPLATES_DATA = {
  page1: [
    "The Journal", "Project Tracker", "Habit Tracker", "Quick Notes", "List To Read - Best for Reader",
    "Smart Bookshelf", "Teachers Video Library", "Goal Manager", "List To-Do in 2023",
    "Content Calendar - Best for Productivity", "Notebook", "Calendar Storyline", "Lead List [Template]",
    "Daily Habit Tracker", "Objective Dairy", "50 States Simple Quest", "Easy Daily Routine Tracker",
    "Notion Helper Bot", "Best Strategy Planner", "Focus & Finish - Project Tracker Notion Template",
    "Business Metrics Log", "Best Subscription Manager", "Unravel GPT-4: A Concise Course",
    "Notion Quick Keyboard Guide", "Easy Content Hub Calendar", "Notes App",
    "90+ Fill-In-The-Blank Hooks For Twitter", "Social Media Manager", "Your Annual Goals",
    "Task Table Manager", "Dating Manager", "Project Research & Freelance Projects",
    "Notebook", "Simple Budget", "Quick Flash Note", "Goal Manager", "Subscription Manager",
    "Complete List Of Task", "Daily Routine Dashboard", "Quicky Journal", "Manage Project",
    "The Daily & Life Goal Pulse", "Unisons Store", "OS Course Schedule", "Easy SWOT Analysis",
    "Easy Subscription Manager", "Plan Meals", "My Daily Planner", "Discover Product", "Ads Code 101"
  ],
  page2: [
    "Subscription Manager", "AI Prompt", "Daily Habit Logger", "Virtual office Meeting Agenda",
    "Personal Journal (Template)", "Percentage Calendar Tracker", "Centre Of Gamification Template",
    "Manage Password", "OS For Software Developer", "Beautiful Moments: Mood Check-In (Basic)",
    "Personal Assistant", "Zapier Automation Guide For Social Media", "Resources & Book Tracker",
    "Easy Notes Board", "Your Personal Notes", "Task Box Pro For Notion", "Finance Tracking",
    "Study Bundle", "Simple Projects - Best for Productivity", "Student Logger", "Ghibli Style Dashboard",
    "Productivity System Of Benjamin Franklin's", "Audience Growth Tool for ChatGPT With Resources",
    "Student Log", "Pet Care Genius", "Smart Education Schedule for everyone", "Personal Goal Tracker",
    "ChatGPT Sandbox: Play and Experiment", "John Doe - CV Template", "Ultimate Code Toolbox",
    "AI Tools - Featured Archive", "Games for Everyone", "Ramadan Life Management",
    "Disease Management", "Daily Routine", "Shop Manager 3.0", "Delicious Delights: A Recipe Hub",
    "Investment Summary Tracker", "CV Template", "Effortlessly Track Your Daily Habits",
    "Airline Tickets Organizer", "Track Your Growth with Colorful Bars", "Finance Management Dashboard",
    "Daily Goals", "Health and Daily Tasks", "Social Media Task Management & Planner",
    "Freelancer's Project Management", "Quick Notes App", "Weekly Plan Manager", "Easy Calendar Tutorial"
  ],
  page3: [
    "Simple Master Calendar", "Task For Life - Planner - Tracker", "Log of Dream",
    "Daily Routine Tasks Journal", "Template For University", "Task Management",
    "Simple Media Manager", "Remaining Task Reminder", "Learning Checklist",
    "Easy Address List", "Women Health", "To-Do Checklist", "Daily Journal Plan",
    "Action Plan Blueprint", "General Life Tracker", "Universal Tagging Made Easy",
    "Tech Code Stack", "Basic Tasks", "Task List Checker", "Simple Flashcards",
    "Daily Detailed Habits Tracker", "Simple Quick Mark Web", "KaTeX Custom Tag Generator",
    "Simple Quad Alert Matrix (tutorial)", "List to Read", "Notes for Meeting",
    "Calendar Habit Tracker", "Documents", "Track Research Of User", "Notion Design Rating System",
    "Smart Folder Organizer", "Simple File Management", "Pomodoro Time and Plan Tracker",
    "Notion Smart Reading Log", "Project Tracker + Invoice", "Simple Meal Log",
    "Tag View Streamline", "Financial Planner", "Food Dashboard", "Simple Journal",
    "Cookbook Box", "Cafe Tracker", "Strategy Planner", "One-On-One Meeting Tracker",
    "Amsterdam Local Living Guide", "Home Personal Growth Guide", "Quick Feedback Design",
    "Design Kit", "Company Hub", "Planned Trip"
  ],
  page4: [
    "Organize Documents", "Investment Monitor", "All-Hands Virtual Meeting Agenda",
    "Birthdays Tracker", "Goal Track journal template", "Closer's Manager",
    "Notion Founder HQ", "eCommerce Task Log", "200+ Notion Templates",
    "Personal Health Tracker", "Track People Birthday", "Dashboard", "CV Template",
    "Climbing plans log - Basic", "Grad school Manager", "Home Sweet Home",
    "Onboarding Newcomers", "Everyday Roadmap", "Yearly Accomplishments Report",
    "Trip Scheduler", "Yearly Accomplishments Report", "Preparation Plan for Earthquake",
    "Startup For 2023", "My Network", "Annually", "Recipe Book", "Food Preparation",
    "Vocab Hub", "Thought Tank", "Decade Assessment", "My Productivity Hub",
    "Focus Hub", "Target Tracker", "Writer Dashboard", "Notion Tweet log",
    "Adventure on Notion (Halloween Special)", "Neon Widgets", "Manage Password",
    "Neon Second Brain", "Books Personal Tracker", "Template Finotion (sample)",
    "Lean Template (Canvas)", "Ravenbright Design Starter Kit: Free Resources for UI/UX Growth",
    "Podcast Guest Log", "Simple Bullet journal", "Productivity Boost Template",
    "Easy Frictionless finance tracker", "Mini Mood tracker", "Recruiting Tracker Dashboard"
  ],
  page5: [
    "Repeatedly Smart System", "Your name (portfolio)", "Manage Invoice",
    "Idea Dashboard OS", "New Years Resolution 2024 [Template]", "Concert Tracker",
    "Daily Mood Logger", "Team Check-In", "Course Navigator", "Bookshelf Picks",
    "Simple Life Dashboard", "1st Semester", "Future Planning", "Life In School Dashboard",
    "Your Special Home", "How to assemble a Notion weather widget", "Protected Pages",
    "Copy Blocks With Drag and Drop", "Change Font", "Permanent Search Engine Indexing",
    "Set Reminders In Notion", "Switch Theme To Dark", "Fast Search in Notion",
    "Mastering the Art of Structuring", "Beginner bundle [Notion]", "SIMPLE HABIT LOG",
    "SaaS Calculator & Cheat Sheet Metrics", "2023 Easy Weekly Planner [TEMPLATE]",
    "Expenses Tracker Shared Version", "Track Habit Weekly", "Career Tracker",
    "Recurring Reviews", "Workspace Kit", "Tax Forms Manager", "Track My Reading",
    "Track Ideas", "Medicine Tracker", "List of To-Dos", "Tv Shows & Movies Tracker",
    "Daily Work Journal", "Goal Process Plan", "One Page Project Manager", "Bio Link",
    "Ordinary Library Template", "Ramadan Calendar & Journal", "Nap Tracker",
    "Color Addition to Notion Databases", "Change Template Colors", "Database Creation",
    "Format a Number as a Percentage or Currency"
  ],
  page6: [
    "Opening Multiple Windows In Notions", "Upload Multiple Media Files to Databases",
    "CRM Business", "Beginners Bundle For Notion", "Business Growth Guide",
    "Education Tutorial", "Cost Marketing Framework", "Music Tutorial",
    "ChatGPT Sandbox", "Mini Dashboard", "Student Plan", "SLEEP Guide",
    "NOTES & IDEAS Capture", "The Dream Job Log", "Easy Team Dashboard",
    "Property Income & Expense Tracker [Rental]", "Extended To-Do List",
    "Twitter Hooks 90+ Fill-In-The-Blank", "Habits & Goals", "Workout & Fitness",
    "Business Lean Canvas & Model Canvas", "Simple Notion CRM",
    "World Of Notion ∙ 150+ Resources to Master Notion", "Content Calendar & Planner[TEMPLATE]",
    "Builder Of Climax | Notion Guide", "Character Development Profile | Notion Worksheet",
    "Story Spark | Notion Guide", "History Timeline Fictional Version | Notion Template",
    "20 Principle Examples Of Designing", "Manage Blogs", "Easy Notebook",
    "Notion Content Short Template from Content Log", "Post Of Blog",
    "Profile Building, bio & picture setup", "Digital Product Ideas 50 plus",
    "Notion Bundle for Beginner", "Organize Books", "Goals Planner",
    "Workspace For Student", "Projects Template", "Archived Bookmarks",
    "Easy Life Tracker", "Your Details", "Trip Planner", "Creators Resources",
    "Free Version Bliss - Access Page", "Shared Expenses Tracker", "CRM Basic Board",
    "Social Media Planner", "Manage Projects"
  ],
  page7: [
    "Track Time", "Life Planner", "Creator Starter Kit", "Mini Dashboard 2.0",
    "Ultimate Workout Planner for Fitness Optimization", "Twitter's Creator",
    "Personal Bullet Journal", "Daily Plan", "Track Habits", "GUMROAD NEWSLETTER GUIDE",
    "STUDENT LOG", "OS Dashboard", "Productive Learning", "Dairy and Notebook OS",
    "OS Sales", "Printable Planners Framework", "Organize Bookmarks", "OS Dashboard",
    "Time Management OS", "Getting Task Done", "Knowledge Box", "Failure Log",
    "Tasks Planner", "Extract Bookish Knowledge", "Launch Sheet", "Business OS",
    "Habit Tracker", "CV Template", "Jobs Management Dashboard",
    "Habit Tracker and Notion Resources", "Easy CRM", "Daily Manifest and Notion Resources",
    "Daily Routine Tracker", "Second Brain and Notion Resources", "Notion AI Crash Course",
    "Progress Tracker", "Tracker for Habits", "HQ Dashboard For Notion",
    "Track Finances", "Goal Planners", "Money Management", "Notion Crash Course",
    "Buttons Habit Tracker", "Matrix Of Eisenhower",
    "An Introduction to Priority Matrix Lite", "Mobile Habit Tracker",
    "Notion Beginner Guide", "CV Builder", "Simple Invoice Template",
    "All-in-One Travel Planner"
  ],
  page8: [
    "To-Do Tracker", "Track Finance", "Manage Task", "Track Habit", "Content Organizer",
    "The Ultimate Expense Tracker", "Online Learning Tracker Guide",
    "Ultimate Goal Tracker", "One Line a Day Journal", "Easy Gratitude Journal",
    "100 New Digital Product Ideas", "Trio Planner for Productivity",
    "Notes For Meeting", "Easy finance tracker", "Track Books", "Travel Dashboard",
    "Keyboard Shortcuts (100+ Shortcuts)", "Upvoting System",
    "Invoice Template Plus Mini Tracker", "Success Blueprint",
    "Start Your Business on Campus with Zero Investment", "Fitness Guide",
    "Establish Goals and Habits", "Vacation Planner", "Contact Organizer",
    "Watch List Manager", "Reading Tracker", "Ramadan Notion Tracker",
    "4-weeks Goal Tracker & Planner", "Notion Habit Planner",
    "Take Control of Your Finances with Monthly Budget Planner", "Podcast Organizer",
    "Notebook Organizer", "Notion Job Search", "Order Tracker", "Bookmark Organizer",
    "Productivity Brain", "Notion Template - Medium.com Writers Dashboard",
    "Social Media Manager", "Balance Tracker", "Productivity Hub", "Travel Log",
    "Habit Planner", "Mood Journal", "Finance Tracker", "Link Present in Bio",
    "Single Page Project Manager", "Easy Habit Tracker", "Goal Action Planner",
    "Easy Library Template"
  ],
  page9: [
    "Bullet Journal and Notion Resources", "OKR Goal Tracker and Notion Resources",
    "Fitness Tracker", "Finance Master", "Weekly Manager", "62 - TEMPLATES",
    "Public Track", "Weekly Planner", "Plan your Meal", "Boost Productivity",
    "112 Ideas to Use ChatGPT", "Class Schedule", "To Do List",
    "Gumroad's Ultimate Newsletter Guide", "Student Goal Planner Premium",
    "Eisenhower Matrix", "Meal Planner", "Christmas Planner", "UX/UI Design",
    "Physics Dashboard Free", "UX/UI Designer Career", "100 Digital Product",
    "Book Tracker", "Ramadan", "Product-Market Fit Canvas", "Config Year 2023",
    "Dump Brain (Anime)", "Mini Meal Planner", "Home Organizer",
    "University - College - School", "Blue CRM Dashboard", "YouTube Organizer",
    "Complete Finance Tracker", "Reading List", "Notes Taking App",
    "Social Media Management", "Notes Management", "Goals Planner",
    "Blogs Plan Management", "Manage Tasks", "Book Reading Management",
    "CRM For Notion", "Monthly Finance Tracker", "6 Day Email Drip Sequence",
    "Twitter Checklist", "Digital Product Checklist", "Story Real Game",
    "Super Easy Habit Planner", "Single Page Project Management"
  ],
  page10: [
    "Library Template", "To Do List", "Daily Routine Journal",
    "Professional Career Compass", "Social Log Management", "Student Center",
    "To-Do List - 2023", "Expense Tracker", "Organized Notebook", "Finance Tracker",
    "Team Planner", "Your Name - Resume Builder", "Best Goal Planner",
    "All-in-one Complete Planner", "INVOICE Number 001 - Template", "Project Tracker",
    "CRM Dashboard", "Team Time Planner", "Unisons eCommerce Store",
    "Mindful Organizer", "Personal Finances", "Personal Project Management",
    "Personal Habit Mastery", "x 9 Notion Mood Emotions",
    "Learn Notion in Just 3 Steps", "Fast Note", "Your Personal Organizer",
    "Daily Task Manager", "Self-Discovery Planner", "Easy List To Read",
    "ChatGPT 100+ Student's Prompts", "700+ Top Tools and Prompts Of AI",
    "ChatGPT Content Marketing 1100+ Expert Prompts", "101 OKR",
    "Brainstorm 250+ Business Ideas with ChatGPT", "15 Copywriting Tutorial",
    "15 Email Marketing Framework", "20 Growth Hacking Roadmap", "16 Write Blog Post",
    "30 Cold DM", "11 Health Coach", "112 AI Generation Character Prompts",
    "20 Copywriting Dashboard", "2 Chef", "16 Coding Framework",
    "15 Social Media Influencer Marketing", "ChatGPT Expert Course",
    "500+ Best ChatGPT Prompts", "101 Call to Action", "101 No Code",
    "E-commerce Code 101", "Ads Code 101", "150+ BEST ENTREPRENEUR TOOLS",
    "1000 Fundamentals Prompts of Product Management",
    "CRM 101: Understanding Customer Relationship Management With ChatGPT"
  ]
} as const;